openapi: 3.0.0
info:
  title: ADS API Specification
  description: This is the API for the IZ Gateway 1.4 Automated Data Submission Service
  contact:
    name: Audacious Inquiry
    email: izgateway@cdc.gov
  version: 1.4.0
servers:
  - url: https://izgateway-dev-nlb-e9941b47428f1e12.elb.us-east-1.amazonaws.com
    description: Development Environment
  - url: https://dev.phiz-project.org
    description: Onboarding Environment
components:
  schemas:
    MetadataResponse:
      type: object
      example: {
          "meta_destination_id": "azurite",
          "meta_ext_submissionperiod": "2023Q1",
          "meta_ext_source": "IZGW",
          "meta_ext_sourceversion": "V2022-12-31",
          "meta_ext_event": "routineImmunization",
          "meta_ext_entity": "MAA",
          "meta_username": "CN=kboone.testing.izgateway.org, O=Audacious Inquiry LLC, L=Baltimore, ST=MaryLand, C=US",
          "meta_ext_filename": "RIA_16M.zip",
          "meta_ext_objectkey": "Write Submission MAA/routineImmuniziation/MAA_16M.zip/2023Q1/RIA_16M.zip with Normalization of Inputs (trimming, capitaliization)",
          "meta_ipaddress": "24.241.16.31",
          "meta_path": "https://127.0.0.1:10000/devstoreaccount1/izgw/2023Q1/MAA/20230301/RIA_16M.zip",
          "meta_schema_version": "1.0",
          "meta_filesize": 1781578,
          "meta_uploaded_timestamp": "Wed, 01 Mar 2023 21:24:59 UTC"
      }       
      properties: 
        meta_destination_id:
          type: string
          description: The destination identifier for the submission.  Fixed to NDLP 
        meta_ext_submissionperiod:
          type: string
          description: The period associated with the submission, date, month or quarter, in YYYYQ#, YYYY-MMM, or YYYY-MM-DD format.
        meta_ext_source:
          type: string
          description: The source of the submission. Fixed to IZGW.
        meta_ext_sourceversion:
          type: string
          description: The version of the protocol supported by the destination endpoint. Fixed to V2022-12-31 
        meta_ext_event:
          type: string
          description: The type of submission (RoutineImmunization or InfluenzaVaccination)
        meta_ext_entity:
          type: string
          description: The identifier for the submitting entity (a.k.a. FacilityID)
        meta_username:
          type: string
          format: X.509 Distinguished Name
          description: The principal associated with the sender's certificate iin X.509 format.
        meta_ext_filename:
          type: string
          description: The name of the file submitted.
        meta_ext_objectkey:
          type: string
          format: uuid
          description: The unique key for the object (a.k.a. MessageID).
        meta_schema_version:
          type: string
          description: The schema version for the metadata.
          enum:
          - "1.0"
        meta_uploaded_timestamp:
          type: string
          description: The timestamp for the uploaded data, an IZ Gateway extension to metadata.
          format: "EEE, dd MMM yyyy HH:mm:ss zzz"
        meta_ipaddress:
          description: The IP Address of the submitting system, an IZ Gateway extension to metadata.
          format: ipAddress
        meta_filesize:
          type: integer
          description: The size of the uploaded file, an IZ Gateway extension to metadata.
        meta_path:
          type: string
          description: The destination path, an IZ Gateway extension to metadata.
          
    ErrorResponse:
      type: object
      example: {
        "eventId": "33",
        "message": "Error in Request: Required request parameter 'reportType' for method parameter type String is not present",
        "code": "003",
        "summary": "Error in Request",
        "diagnostics": null,
        "detail": "Required request parameter 'reportType' for method parameter type String is not present",
        "retryStrategy": "CORRECT_MESSAGE",
        "faultName": "MissingServletRequestParameterException"
      }
      properties:
        eventId:
            type: string
            description: The IZ Gateway unique event id for this request used to correlate this event in diagnostic logs. Report this identifier in error reports submitted to izgateway@cdc.gov 
        message: 
            type: string
            description: The complete description of the error.
        code:
            type: string
            description: The error code associated with the error.
        summary:
            type: string
            description: A brief description of the error used for aggregating metrics.
        diagnostics:
            type: string
            description: Diagnostics appropriate for correcting the problem.
        detail:
            type: string
            description: Specific exception detail.
        retryStrategy:
            type: string
            description: >
                The retry strategy
                  * `NORMAL`: Apply normal message retry strategy (e.g., wait a minute and try again, if that fails wait longer, and if that fails try much later). 
                  * `CORRECT_MESSAGE`: Correct the message before sending again. 
                  * `CONTACT_SUPPORT`: Contact IZ Gateway support via mailto:izgateway@cdc.gov for assistance. 
                  * `CHECK_IIS_STATUS`: Check the status of the destination (see https://status.izgateway.org) 
            enum:
              - NORMAL 
              - CORRECT_MESSAGE 
              - CONTACT_SUPPORT 
              - CHECK_IIS_STATUS 

paths:
  /rest/ads/{destinationId}:
    parameters:
      - name: destinationId
        description: >
          The identifier of the destination expected to receive the content.
            * `ndlp-izgw-ri` - Destination for routine immunization submissions
            * `ndlp-izgw-flu` - Destination for influenza submissions
            * `azurite` - A test endpoint for Phase 1 (ndlp). Data sent to this endpoint verifies the ability to transmit a file to IZ Gateway but will be discarded.
            * `dex-dev` - A test endpoint for Phase 2 (DEX). Data sent to this endpoint verifies the ability to transmit a file to IZ Gateway but will be discarded.
            * `dex-stg` - Destination for submissions through (DEX), currently only supporting routing immunization submissions.
        in: path
        schema:
          type: string
          enum:
          - ndlp-izgw-ri
          - ndlp-izgw-flu
          - azurite
          - dex-dev
          - dex-stg
        required: true
      - name: X-Message-ID
        in: header
        description: A unique message identifier used to track the transmission. If this or one of the following omitted, a random UUID will be generated by IZ Gateway. 
        schema:
          type: string
          format: uuid
          description: Message IDs and their alternatives below are expected to be provided in UUID format, but IZ Gateway will accept any string as a message ID.
        required: false                    
      - name: X-Correlation-ID
        in: header
        description: Alternative to X-Message-ID (the preferred header field). 
        schema:
          type: string
          format: uuid
        required: false                    
      - name: X-Request-ID
        in: header
        description: Another alternative to X-Message-ID (the preferred header field). 
        schema:
          type: string
          format: uuid
        required: false  
    post:
      tags:
        - default
      summary: Send a file to the selected destination
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required: [ "facilityId", "file", "period", "reportType" ]
              properties:
                facilityId:
                  description: The identifier for the jurisdiction or facility sending data. Typically the two letter state abbreviation followed by A. Assigned by the IZ Datalake team to each jurisdiction.  
                  type: string
                  example: MAA
                filename:
                  description: The filename to use for this submission. Can be used to override the filename supplied by a web browser when using a file form component.
                  type: string
                  example: MAA_16M.zip
                file:
                  description: The file to send to the destination. This should be a zipped up file containing the components of the Routine Immunization or Influenza reports.
                  type: string
                  format: binary
                period:
                  description: The period associated with the report.  Should be in YYYYQ# format, or YYYY-MMM format.  E.g., 2023Q1 or 2023-FEB
                  type: string
                reportType:
                  type: string
                  enum:
                  - routineImmunization
                  - influenzaVaccination
                  description: >
                    The type of report to send.
                      * `routineImmunization` - A routine immunization report. Typically send quarterly by jurisdictions.
                      * `influenzaVaccination` - An influenza report. Typically send monthly by jurisdictions.
                
      responses:
        '200':
          description: Successful response. The content of this response contains a copy of the metadata that is transmitted to the IZ Datalake (or the test endpoint).
          content:
            application/json: 
              schema:  
                $ref: '#/components/schemas/MetadataResponse'

        '400':
          description: Invalid request. The request needs to be corrected before sending again.
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Destination was not found. Correct the destinationId in the URL.
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An error occured in the IZ Gateway application.  Contact support via izgateway@cdc.gov.
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Destination returned an invalid response.
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: The request could not be completed at this time. The request can be reattempted at a later time.   
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/ErrorResponse'
